# -*- coding: utf-8 -*-
"""Aux 6 .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TSsasF2tw5sO0e-abh0nHmy5O9WTwyR7

#Auxiliar 6 


P1. Considere que tiene la estructura Animal que tiene como atributos Especie, Clase, Dieta y Edad(en meses). Se le entregará una lista de Animales y se le solicita que realice lo siguiente:

1. Cree la función esClase(A,clase) que verifique si el animal A es de la clase indicada
2. Cree un filtro que reciba una Lista de animales y una clase, y entregue una lista con los animales que son de la clase indicada
3. Cree Agnos(A), que reciba un Animal y convierta su edad a años (puede truncar) y además cree mapaAgnos(L) que obtenga una lista de animales y entregue la lista con las edades de los animales en años.
4. Cambie, para todos los animales de la lista, su dieta de por ejemplo Carnivoro a Come Carne.


Clases de Animales: Mamífero, Pez, Ave, Anfibio y Reptil

Dietas de Animales: Carnivora, Hervivora y Omnivora
"""

import estructura as es

es.crear('Animal', 'Especie Clase Dieta Edad')

#codigo

"""P2. El Kino es un popular juego de lotería chileno que consiste en elegir 14 números del 1 al 25 (distintos)
y recibir un premio en función de un sorteo aleatorio. A continuación crearemos un programa para
jugar Kino.



1.   Cree la estructura Kino, la cual consta de una lista de 14 enteros (del 1 al 25, sin repetición y ordenada ascendentemente), un string Fecha de forma "DD/MM/AAAA" (que representa la fecha en que el boleto fue comprado) y un string Comprador que representa de quien efectuó la compra.
2.   Cree la función esKino(kino), que se asegure que los atributos de un Kino nombrados anteriormente sean de la forma correcta (retorna True si lo son, False si no).
3. Cree la función xEstaEnL(x,L) que verifique si el numero x esta en la lista L
L
4. Cree la funcion numerosGanadores() que entregue un lista con 14 numeros distintos, los que corresponderán a los numeros ganadores del kino 
5. Cree la funcion numerosIguales(L1,L2) que recibe dos listas y entrega la cantidad de numeros de la lista 1 que estan en la lista 2 
6. Cree la función imprimir lista, que imprima todos los elementos de una lista 
7. Cree la función sortearKino(L) que, recibiendo una lista de Kinos, simule un sorteo aleatorio del Kino e imprima lo siguiente: si un Kino coincide con entre 14 y 10 números, debe imprimir en pantalla ’Premio X’ (si coincide con 14 números, la función muestra ’Premio 1’, si coincide con 13 muestra ’Premio 2’ y así hasta el 5to premio), junto con el nombre de el/los ganadores, y en cualquier otro caso la función muestra "No hay ganadores".
    Por ejemplo (caso varios ganadores):
    
    listaConocida = lista(Kino1,...)
    
    sortearKino(listaConocida)
    
    Premio 1 Elmer Figueroa
    
    Premio 3 Luis M. Gallego
"""

#codigo