# -*- coding: utf-8 -*-
"""Auxiliar_3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pTMUr8XMvJMmg3KQyBPKO51yAbo9h6aR

#Auxiliar 3 - Recursión


P1. Cree la función maxComunDiv(n,m) que entregue el máximo común divisor de los números enteros n y m entregados. Siga el algoritmo recursivo de Euclides para su construcción. 

Algoritmo de Euclides: 
- maxComunDiv(n,m) = n si n==m
- si n<m -> maxComunDiv(n,m-n)
- si n>m -> maxComunDiv(n-m,m) 

Ej: maxComunDiv(12,40) = 4
"""

#Codigo

"""P2. Defina la función elMayor(n), que a partir de un número entregado devuelva el mayor de ss dígitos. 

Ej: elMayor(257926) = 9
"""

#Codigo

"""P3. Cree la función invertir(n) cuya función es invertir el número n, el cual tiene una catidad cualquiera de digitos. 

Ejemplo: 

```
 invertir(123456) = 654321
```
"""

#Codigo

"""P4. Cree de forma recursiva el programa interactivo calculadoraNotas() el cual le vaya pidiendo sus notas y las vaya almacenando junto con la cantidad de notas que ha ingresado. Cuando quiera que el programa deje de funcionar y le entregue el resultado, el usuario deberá ingresar el número: 0, con esto se calculará el promedio con las notas ingresadas y se le aplicará el redondeo al primer dígito, mostando en pantalla `Su nota final es: ` + la nota calculada. En el caso de que el numero entregado sea menor a 1.0 o mayor a 7.0, el programa mostrará en pantalla `Nota invalida` y seguirá corriendo, sin contar la nota ingresada erroneamente.

Ejemplo: 


```
 Ingrese una nota entre 1.0 y 7.0: 4.1
 Ingrese una nota entre 1.0 y 7.0: 7.8
 Nota invalida
 Ingrese una nota entre 1.0 y 7.0: 4.3
 Ingrese una nota entre 1.0 y 7.0: 0
 Su nota final es: 4.2 
```
"""

#Codigo

"""P5. Cree la función sumaDigitos(n) la cual va a sumar todos los digitos de el número entregado. 

Ejemplo:


```
 sumaDigitos(12345) = 15
```
"""

#Codigo

"""P6. Existe una montaña rusa que posee un sensor de movimiento en la base, el cual va midiendo la altura con respecto al suelo cada cierto tiempo, opteniendo valores enteros entre 1 y 9, considerando que 1 coresponde a 10 metros y las medidas se redondean. 

Los resultados finales entregados por este sensor son enteros que corresponden a las medidas tomas concatenadas, de forma que el entero 14562 corresponde a las alturas aproximadas de 10, 40, 50, 60 y 20, en ese orden.

Creeuna función llamada `diferenciaMax(n)` que dado un entero como el descrito anteriormente devuelva la mayor diferencia (en valor absoluto) entre dos alturas contiguas.

Ejemplo: 


```
 diferenciaMax(14562) 
 40 
```
"""

#Codigo