# -*- coding: utf-8 -*-
"""Auxilliar 4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Zw4Rc3mzVR7BCK60uzm-bCYbmv5ULfpw

#Auxiliar 4 - Recurrencia 

P1. Un niño está aburrido en su casa, por lo que comienza a sumar los dígitos de los número hasta llegar a un solo dígito. Viendo los resultados que obtiene le surge una duda, ¿qué tan frecuente es obtener uno de estos dígitos?. Su trabajo es resolver esta duda, para eso siga los siguientes pasos: 
 
i) Modifique la función sumaDigitos(n), vista en la auxiliar pasada, para que entregue un único dígito

ii) Cree la función contarFrecuenciaDigito(d,N)que dado un dígito d y un natural N, retorne la cantidad de números entre 0 y N, cuya suma de dígitos corresponda a d. Ejemplo: contarFrecuenciasDigito(1,100) = 12 , ya que tenemos los numeros 100, 91, 82, 73, 64, 55, 46, 37, 28, 19, 10 y 1. Al sumar los dígitos de cada uno de ellos nos va a entregar el valor 1. 

iii) Finalmente cree un programa que le solicite el dígito y un natural y le entregue la frecuencia con la que aparece el dígito entre el 0 y el natural ingresado. El programa debe preguntar si quiere volver a consultar y reiniciarse en el caso de que sí.  Para esto, use las funciones definidas anteriormente. 
 

```
Ejemplo: 
  Ingrese el dígito cuya frecuencia busca: 1
  Ingrese hasta que número se debe revisar: 100
  El dígito 1 se repite 12 veces
  ¿Volver a calcular?: si
  Ingrese el dígito cuya frecuencia busca: 0
  Ingrese hasta que número se debe revisar: 100
  El dígito 0 se repite 1 vez 
  ¿Volver a calcular?: no
```
"""

#sumaDigitos(n): int -> int 
#Suma los digitos de un numero
#sumaDigitos(12345) = 15

def sumaDigitos(n):
  if n<10:
    return n
  else: return n%10 + sumaDigitos(n//10)

"""P2. Escriba la función sumaProductos(x,y) que reciba dos enteros positivos y entregue la suma de los productos de sus dígitos. 
```
Ejemplo: sumaProductos(12345,6789)=110
```

Lo que corresponde a 5x9 + 4x8 + 3x7 + 2x6 + 1x0 = 45 + 32 + 21 + 12 + 0 = 110
"""