# -*- coding: utf-8 -*-
"""Auxiliar1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/bpoblete/CC1002/blob/master/Auxiliares/Auxiliar1/Auxiliar1.ipynb

# Auxiliar Semana 1

## Pregunta 1
Cree una funcion con su receta de disenno que reciba un numero de dos digitos
los invierta de posicion.

EG: invertir(24) -> 42
"""

#
# RECETA
#
def invertir(n):

"""## Pregunta 2
Cree una funcion con su receta de disenno que reciba un entero N y retorne la suma de todos los enteros desde 1 hasta N.

EG: sumEnteros(100) = 5050
"""

#
# RECETA
#
def sumEnteros(n):

"""## Pregunta 3
Cree una funcion con su receta de disenno que reciba dos enteros X, Y (X$\le$Y) y retorne la suma de todos los enteros desde X hasta Y.

EG: sumEnterosEnRango(5, 10) = 40
"""

#
# RECETA
#
def sumEnterosEnRango(x, y):

"""## Pregunta 4
Cree una funcion **hoyEs(n)** con su respectiva receta de disenno que reciba un entero de ocho digitos de la forma YYYYMMDD, y retorne un string que diga "Hoy es DD del MM del anno YYYY"

EG: hoyEs(20200831) -> "Hoy es 31 del 08 del anno 2020"
"""

#
# RECETA
#
def hoyEs(n):

"""## Pregunta 5
Cree una funcion **minToHora(min)** con su receta de disenno que reciba una cantidad entera de minutos y retorne un string de la forma "HH:MM" que represente la cantidad de minutos entregados en horas

EG: minToHora(150)->"2:30"
"""

#
# RECETA
#
def minToHora(n):

"""## Pregunta 6
Usando las funciones hoyEs y minToHora cree una nueva funcion **ahoraEs(n):** que reciba un entero de 12 digitos de la forma YYYYMMDDHHHH y retorne la frase "Hoy es DD del MM del anno YYYY, y la hora actual es JJ:KK", donde JJ:KK son HHHH minutos transformados a horas.

EG: ahoraEs(202008310150) -> "Hoy es 31 del 8 del anno 2020, y la hora actual es 2:30"
"""

#
# RECETA
#
def ahoraEs(n):