# -*- coding: utf-8 -*-
"""Auxiliar5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hKsf91mZiMWn2p78oElmGCU_2R5JKVOL

## **Auxiliar 5**

## Pregunta 1

En esta pregunta usted deberá crear una función que determine la cantidad de puntos que pertenecen a una cierta circunferencia. Para esto deberá seguir los siguientes pasos:


1.   Cree la estructura **punto2D**, que contenga 2 parámetros (x, y).
2.   Programe la función **distancia(p1, p2)**, que dado dos puntos2D determine la distancia entre ambos puntos.
3.   Programe la función **pertenece(c, r, p)**, que dado un punto2D *p*, determine si este pertenece a la circunferencia de radio *r* y centro *c* (también de tipo punto2D). Un punto pertenece a una circunferencia, si este se encuentra dentro de la circunferencia o sobre su contorno.
4.   Programe la función **cuantosPertenecen(c, r, l)**, que dado una lista de punto2D (*l*), determine la cantidad de punto2D que pertenecen a la circunferencia de radio *r* y centro *c*.
"""

# P1.1

# P1.2

# P1.3

# P1.4

"""## Pregunta 2

Programe la función recursiva **evaluarPolinomio(l, x)**, la cual recibe una lista de números reales (que representan los coeficientes de un polinomio), y un número *x*, retornando el valor del polinomio al evaluarlo en *x*.

Por ejemplo, sea la lista:

*L = crearLista(0, crearLista(-1, crearLista(1, listaVacia)))*

la cual representa al polinomio *-x + x^2*, entonces **evaluarPolinomio(L, 2)** debe retornar 2.
"""

# P2