# -*- coding: utf-8 -*-
"""EnunciadoAuxiliar8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1N5bBYn4UnkxEz_bd2OImYXH_CJa4e2Ye

#Auxiliar 8 - Mutación y Aliasing

### P1. ONU
La ONU requiere su ayuda manteniendo un registro actualizado de los mandatarios de todos los países del mundo. Para esto desarrollaremos una función que permita cambiar el nombre del presidente de un país.

### A)
Cree la estructura **no mutable** llamada 'Pais' que tenga los atributos nombre, continente y presidente_actual.

### B)
Cree la estructura **mutable** PaisMut con los atributos nombre, continente y presidente_actual.

### C)
Defina la función cambioDeMando, que recibe un **Pais** y el nombre de un presidente, y retorne un Pais con el nuevo nombre del presidente.

### D)
Defina la función cambioDeMandoMut, que recibe un **PaisMut** y el nombre de un presidente y actualiza el nombre del presidente de PaisMut en cuestión. Esta función debe retornar None.

### P2. Convivencia
Cuando acabe la pandemia organizaremos una convivencia del curso. Para esto crearemos un programa que nos permita llevar un registro de los participantes y las cosas que traerá cada uno.

Para resolver el ejercicio, utilice la funcion buscar y las estructuras mutables lista, producto y participante definidas a continuación.
"""

import estructura

# participante: nombre(str) confirmacion(str) nombre_producto(str)
estructura.mutable('participante', 'nombre confirmacion nombre_producto')
# producto: nombre(str) cantidad(int)
estructura.mutable('producto', 'nombre cantidad')
# lista: valor(producto o participante) siguiente(lista)
estructura.mutable('lista', 'valor siguiente')

# buscar: lista(producto o participante ), string -> producto o participante 
# Recibe una lista de las estructuras producto o participante y un parámetro nombre. 
# Busca el elemento de la lista cuyo atributo nombre sea igual al parámetro nombre. 
# Ej: 
# producto1 = producto("chips pop", 5)
# producto2 = producto("bebidas", 0)
# L1 = lista(producto1,(lista(producto2, None)))
# buscar(L1, "chips pop")
# assert buscar(L1, "chips pop") == producto1

# participante1 = participante("Camila", "no", None)
# participante2= participante("José", "no", None)
# L2 = lista(participante1,lista(participante2, None))
# assert buscar(L2, "José") == participante2

def buscar(L, nombre, value=None):
  if L== None:
    return None
  if L.valor.nombre==nombre:
    value= L.valor
    return value
  else: 
    return buscar(L.siguiente, nombre)


producto1 = producto("chips pop", 5)
producto2 = producto("bebidas", 0)
L1 = lista(producto1,(lista(producto2, None)))
buscar(L1, "chips pop")
assert buscar(L1, "chips pop") == producto1

participante1 = participante("Camila", "no", None)
participante2= participante("José", "no", None)
L2 = lista(participante1,lista(participante2, None))
assert buscar(L2, "José") == participante2

"""### A)
Defina e inicialice con None las variables de estado participantes e inventario. 
La variable participantes será una lista de elementos de tipo participante, y nos permitirá llevar un registro de quienes irán o no a la convivencia. Por otro lado, inventario será una lista de elementos de tipo producto en la que iremos agregando las donanciones de cada participante.

### B)
Defina la función editarConfirmacionParticipantes. Esta recibirá el nombre de la persona (nombre) y la decisión de si irá o no a la convivencia (confirmacion). Esta función debe editar el atributo confirmacion de la persona con el nombre dado. Además, si la persona no estaba registrada, se agrega a la lista de participantes con el estado indicado en confirmacion.

Esta función no debe retornar nada. Pero debe imprimir el valor anterior y el nuevo de confirmacion. Para el caso en el que se agregue un nuevo participante se debe imprimir el nombre de quien se agregó y el valor actual de su confirmacion.

Ejemplos de mensajes:

i) Caso en el que existe el participante:


```
La confirmación cambió, antes era no
ahora es sí
```

ii) Caso en el que se agrega a alguien:

```
Se agregó a Juanita con confirmación sí
```

Utilice la función buscar y la variable global participantes. Además asuma que los nombres de los asistentes son únicos.

### C) 
Defina la función editarInventario. Esta recibirá el nombre de un producto de la lista inventario y un parámetro delta, el que puede ser 1 o -1. En el primer caso indicará que se aumenta en 1 la cantidad de productos y en caso de ser -1 indicará que este se debe disminuir en uno.

Si al disminuir los productos se obtiene cero o un valor negativo, no se debe eliminar el producto, basta con que el parametro cantidad sea cero. Por otra parte si el producto no se encuentra se debe agregar a la lista inventario. 

Esta función no debe retornar nada. Pero debe imprimir el nombre del producto, junto con el valor anterior y el nuevo de cantidad. Para el caso en el que se agregue un nuevo producto se debe imprimir el nombre del producto que se agregó. En el caso de que se disminuyan los productos a 0 se debe indicar el nombre del producto que se acabó. 


Ejemplos de mensajes:

i) Caso en el que existe el producto y este se aumenta:


```
La cantidad de papas cambió, antes era 1
ahora es 2
```

ii) Caso en el que se agrega un nuevo producto:

```
Se agregó el producto papas
```
iii) Caso en el que se acaba un producto:

```
Ya no quedan papas
```

Utilice la función buscar y la variable global inventario. Además asuma que los nombres de los productos son únicos.

### D)
Utilizando las variables globales participantes e inventario y las funciones buscar, editarConfirmacionParticipantes y editarInventario, cree un programa interactivo que siga el siguiente diálogo. 

En negritas están los mensajes nuevos que debes agregar al usuario, estos sólo son de tipo input. El resto de los mensajes ya deben haber sido programados en las funciones que definimos anteriormente.

**¿Salir?** no

**¿Cómo te llamas?** María

**¿Vendrás a la convivencia?** sí

Se agregó a  María con confirmación  sí

**¿Qué traerás?** papas

Se agregó el producto  papas

**¿Salir?** no

**¿Cómo te llamas?** Javier

**¿Vendrás a la convivencia?** sí

Se agregó a  Javier con confirmación  sí

**¿Qué traerás?** papas

La cantidad de  papas cambió, antes era  1

ahora es  2

**¿Salir?** no

**¿Cómo te llamas?** Pepe

**¿Vendrás a la convivencia?** no

Se agregó a  Pepe con confirmación  no

**¿Salir?** no

**¿Cómo te llamas?** María

**¿Vendrás a la convivencia?** no

La confirmación cambió, antes era  sí

ahora es  no

La cantidad de  papas cambió, antes era  2

ahora es  1

**¿Salir?** si
"""