# -*- coding: utf-8 -*-
"""Aux9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1o-aa95ClnyiGrvleazz-AMCowWy-4bOz

Auxiliar 9





P1) Cree la función quitar(a,b), que recibe como parámetros dos números enteros a y b, que indican dos índices de una lista de python (a <=b). La función debe modificar la lista global L, eliminando todos los elementos ubicados entre los  índices a y b (inclusive). La función entrega como resultado,la cantidad de elementos que fueron borrados de la lista. Si alguno de los índices se encuentra fuera del rango de la lista, la función solo elimina los valores que estén dentro del rango. Ejemplos:

```

L = [79, 45, 18, 64, 17, 24, 51] 

quitar(7,9)-> entrega 0, y L queda como: L= [79,45, 18, 64, 17, 24, 51]

quitar(3,5)-> entrega 3, y L queda como: L= [79,45,18,51]


L = [79,45,18,64,17,24,51] 

quitar(5,8)-> entrega 2, y L queda como: L= [79. 45,18,64,17] 

quitar(2,2)-> entrega 1, y L queda como: L= [79,45,64,17]

```
"""

# Codigo

"""P2) Se le pide crear un sistema de notas interactivos para el curso de programación con el cual debe poder agregar notas de alumnos, quitar, consultar notas por alumno, mostrar todas las notas del curso o sacar el promedio. Para esto debe manejar dos listas (una de los nombres y otra de las notas). Programe las siguientes funciones:

**insertarNota(alumno, nota):** Inserta el nombre del alumno con su respectiva nota.

**quitarNota(nombre):** Quita la nota y al alumno, retornando que nota fue retirada

**consultarNota(nombre):** Entrega la nota correspondiente al alumno.

**mostrarNotas():** Imprime en pantalla todas las notas del curso

**promedio()**: Entrega el promedio del curso

Las listas son del tipo global

Luego cree un programa interactivo de sistema de notas que se comporte de la siguiente manera:

```
Sistema de notas
Opciones: 1-Agregar nota, 2-Quitar nota, 3-Consultar nota, 4-Mostrar notas, 5-Promedio
Eliga que opcion quiere ejecutar: 1
Inserte nombre del alumno; Pepe
Ingrese nota del alumno: 50
Opciones: 1-Agregar nota, 2-Quitar nota, 3-Consultar nota, 4-Mostrar notas, 5-Promedio
Eliga que opcion quiere ejecutar: 1
Inserte nombre del alumno: Juan
Ingrese nota del alumno: 30
Opciones: 1-Agregar nota, 2-Quitar nota, 3-Consultar nota, 4-Mostrar notas, 5-Promedio
Eliga que opcion quiere ejecutar: 4
Alumno: Pepe Nota: 50.0
Alumno: Juan Nota: 30.0
Opciones: 1-Agregar nota, 2-Quitar nota, 3-Consultar nota, 4-Mostrar notas, 5-Promedio
Eliga que opcion quiere ejecutar: 5
40.0
Opciones: 1-Agregar nota, 2-Quitar nota, 3-Consultar nota, 4-Mostrar notas, 5-Promedio

Eliga que opcion quiere ejecutar 
```
"""

#Codigo

# Programa interactivo

"""P3) Un palíndromo, es una palabra o frase que se lee igual en un sentido que en otro. Cree una función esPalindromo que verifique si un string es un palindromo o no. Para esto no puede crear un nuevo string, debe manejar dos variables, una que lea desde el inicio y otra desde el final."""

# Codigo